/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class EdgeClient {
  constructor(serverAddr: string, token: string, forwardTo: string)
  connect(): void
  disconnect(): void
  invoke(command: string, data: string): string
}

export declare function connectToServer(serverAddr: string, token: string, forwardTo: string): void
